# Generated by Django 3.2.12 on 2022-03-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20220307_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctor'),
        ),
    ]
