# Generated by Django 3.2.12 on 2022-03-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_patient_assigned_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
