# Generated by Django 3.2.12 on 2022-03-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_scans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scans',
            new_name='Scan',
        ),
    ]
